spring:
  datasource:
    url: jdbc:postgresql://hack-db:5432/${PG_DB}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  minio:
    endpoint: http://minio:9000
    endpoint-download: http://localhost:9003

