spring:
  datasource:
    url: jdbc:postgresql://hack-db:5432/${PG_DB}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: hack_redis
      port: 6379

app:
  minio:
    endpoint: http://minio:9000
    endpoint-download: https://bobr.kinoko.su
